engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
ratings:
  paths:
  - "src/**.js"
exclude_paths:
- benchmark/
- build/
- dist/
- examples/
- node_modules/
- test/
- vendor/
- "*.js"
- "*.json"
- "*.md"
