language: node_js
node_js:
  - "0.10"
env:
  global:
    - GHPAGES=".gh-pages"
    - secure: "TiAOsFfGlvE+wwDoMxYxlMnbJ/ey0c1KsHYahTA78zu5aHVGksOsjKKfZTcrl7Eiup5KSLcpcD1FXDIpUGNggO1b1w/nt8SLI8X0qTRpgVUUHVVnGAuSeg1+TmoVUcM//RSJwTaQrzqQCyqJtGehumV2Y9DA7WSLywzWx/4bPMQ="
    - secure: "Vd/5T6hDx+XSbZsVVAICuYPKLj6DnEeX7uDR2C7n/JfXH1RaGmlhm2Q8Iv1KjduBk6ro6aSKYh/wlSnKWe3LJVxSN+f7XSkudohS/ogCzo4U740YQ8j/0NPF6SccYp9ukNvkH1hsawpxl/GBl2FKDUInNzLuTply23sn+LncUbE="
    - secure: "FpgwXfgX7oDBSUMOjO9pvdjg2ZnzNr0oPUxz6sdiZCZE2P7Tda/AJqt4RQNOo+f+MwYMA818ykuIOrI7J88MH07KZSR86bYnTldls9T+IJ4TPskNstiCuZ9p+LQi0dWsC65vUhrNObGbQ+bAsf8cnMqd6kxVgaInhd+5ixxET6k="
branches:
  only:
    - master
before_install:
  - "npm i coveralls ecstatic request sauce-tunnel"
before_script:
  - "./node_modules/gulp/bin/gulp.js build-release"
script:
  - "npm test"
after_success:
  - "npm run coverage"
  - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
  - "git config --global user.email \"travis@travis-ci.org\" && git config --global user.name \"travis-ci\""
  - "git clone --branch=gh-pages https://${GH_TOKEN}@github.com/webpro/jquery-evergreen.git $GHPAGES"
  - "cat $GHPAGES/index.yml README.md > $GHPAGES/index.md"
  - "rsync --recursive --delete dist/ $GHPAGES/dist/"
  - "rsync --recursive --delete test/ $GHPAGES/test/"
  - "rsync --recursive --delete benchmark/ $GHPAGES/benchmark/"
  - "rsync --recursive --delete coverage/lcov-report/ $GHPAGES/coverage/"
  - "cp coverage/coverage.json coverage/lcov.info $GHPAGES/coverage/"
  - "rm -rf $GHPAGES/doc && ./node_modules/doxstrap/bin/doxstrap.js --title \"jQuery Evergreen\" --output $GHPAGES/doc"
  - "cd .release/commonjs && ../../node_modules/plato/bin/plato -r -d ../../$GHPAGES/complexity --jshint ../../.jshintrc ."
  - "cd $TRAVIS_BUILD_DIR"
  - "gulp clean"
  - "cd $GHPAGES && git add --all && git commit -m \"Update all the things\" && git push -fq origin gh-pages > /dev/null"
  - "cd $TRAVIS_BUILD_DIR"
  - "node test/lib/sauce.js"
  - "rm -rf ./coverage $GHPAGES"
